-- MySQL Script generated by MySQL Workbench
-- 03/25/17 15:50:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tallerarquitectura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tallerarquitectura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallerarquitectura` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tallerarquitectura` ;

-- -----------------------------------------------------
-- Table `tallerarquitectura`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`empresa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `mision` TEXT NOT NULL COMMENT '',
  `vision` TEXT NOT NULL COMMENT '',
  `valuacion` TEXT NOT NULL COMMENT '',
  `objetivo` TEXT NOT NULL COMMENT '',
  `ubicacion` VARCHAR(255) NOT NULL COMMENT '',
  `correo_electronico` VARCHAR(150) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`miembros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreCompleto` VARCHAR(255) NOT NULL COMMENT '',
  `foto` VARCHAR(255) NOT NULL COMMENT '',
  `profesion` VARCHAR(200) NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `empresa_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `empresa_id`)  COMMENT '',
  INDEX `fk_miembros_empresa_idx` (`empresa_id` ASC)  COMMENT '',
  CONSTRAINT `fk_miembros_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `tallerarquitectura`.`empresa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(200) NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `imagen` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`subcategoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(255) NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `destacado` VARCHAR(1) NOT NULL COMMENT '',
  `categoria_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `categoria_id`)  COMMENT '',
  INDEX `fk_subcategoria_categoria1_idx` (`categoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_subcategoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `tallerarquitectura`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`imagen_subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`imagen_subcategoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `imagen` VARCHAR(255) NOT NULL COMMENT '',
  `subcategoria_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `subcategoria_id`)  COMMENT '',
  INDEX `fk_imagen_subcategoria_subcategoria1_idx` (`subcategoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_imagen_subcategoria_subcategoria1`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `tallerarquitectura`.`subcategoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`video_subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`video_subcategoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `video` VARCHAR(255) NOT NULL COMMENT '',
  `subcategoria_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `subcategoria_id`)  COMMENT '',
  INDEX `fk_video_subcategoria_subcategoria1_idx` (`subcategoria_id` ASC)  COMMENT '',
  CONSTRAINT `fk_video_subcategoria_subcategoria1`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `tallerarquitectura`.`subcategoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(200) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `tipo` VARCHAR(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallerarquitectura`.`redsocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallerarquitectura`.`redsocial` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `url` VARCHAR(255) NOT NULL COMMENT '',
  `empresa_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `empresa_id`)  COMMENT '',
  INDEX `fk_redsocial_empresa1_idx` (`empresa_id` ASC)  COMMENT '',
  CONSTRAINT `fk_redsocial_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `tallerarquitectura`.`empresa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
